AllCops:
  DisplayCopNames: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false